name: zarr-cache
channels:
  - conda-forge
dependencies:
  # Runtime libs
  - boto3>=1.14
  - botocore>=1.17
  - numpy>=1.19
  - s3fs>=0.4
  - zarr>=2.4
  # Test dependencies
  - dask>=2.24
  - xarray>=0.16
  - moto
  - flake8
  - pytest
  - pytest-cov
